---
# Main

- name: Install NGINX for AWS
  include: aws.yml
  become: yes
  when:
    - "{{ ansible_distribution == 'Amazon' }}"
  tags:
    - packages
    - install
    - update

- name: Install NGINX for AWS
  include: ubuntu.yml
  become: yes
  when:
    - "{{ ansible_distribution == 'Ubuntu' }}"
  tags:
    - packages
    - install
    - update


- name: Configure NGINX
  include: config.yml
  become: yes
  tags:
    - config
