---
# Install and configure the root of NGINX


- name: Install NGINX from AWS Repos
  apt:
    name: nginx
    state: latest
    disablerepo: epel
  tags:
    - preinstall
  become: yes
  register: nginx_install

- name: Stop NGINX
  service:
    name: nginx
    state: stopped
  when:
    - not nginx_install|changed
  tags:
    - install
  become: yes
