---
# Install and configure the root of NGINX


- name: Install NGINX
  apt:
    name: nginx
    state: latest
  tags:
    - preinstall
  become: yes
  register: nginx_install

- name: Stop NGINX if not installed already
  service:
    name: nginx
    state: stopped
  when:
    - not nginx_install|changed
  tags:
    - install
  become: yes
